// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44ZQgMC2Do7XFhyl9DOSFQ-lD_QuFIkI',
    appId: '1:413949886964:web:97b555e471d01e71abb9a1',
    messagingSenderId: '413949886964',
    projectId: 'home-coach-e0e0c',
    authDomain: 'home-coach-e0e0c.firebaseapp.com',
    storageBucket: 'home-coach-e0e0c.appspot.com',
    measurementId: 'G-CCTQKKG4FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGwbEaDiJrjTwoKDyccF-GOrC8gZmbRI',
    appId: '1:413949886964:android:cef4295cee24c9afabb9a1',
    messagingSenderId: '413949886964',
    projectId: 'home-coach-e0e0c',
    storageBucket: 'home-coach-e0e0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPLcPLo41jGRHl8Nqb3vEPiRPT4INAw0',
    appId: '1:413949886964:ios:57c969c075dce922abb9a1',
    messagingSenderId: '413949886964',
    projectId: 'home-coach-e0e0c',
    storageBucket: 'home-coach-e0e0c.appspot.com',
    iosClientId: '413949886964-medeup85atimalqhh4dqsdpok10hhs7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzPLcPLo41jGRHl8Nqb3vEPiRPT4INAw0',
    appId: '1:413949886964:ios:57c969c075dce922abb9a1',
    messagingSenderId: '413949886964',
    projectId: 'home-coach-e0e0c',
    storageBucket: 'home-coach-e0e0c.appspot.com',
    iosClientId: '413949886964-medeup85atimalqhh4dqsdpok10hhs7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeCoach',
  );
}
